sudo: false

language: python

matrix:
  include:
    # OSX doesn't work with `language: python` yet
    - os: osx
      language: generic
    #- os: linux
    #  python: 2.6
    #- os: linux
    #  python: 2.7
    #- os: linux
    #  python: 3.4
    #- os: linux
    #  python: 3.5
    #- os: linux
    #  python: pypy

addons:
  apt:
    packages:
      - libenchant-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf ./enchant; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install https://pypi.python.org/packages/4f/c5/5c18df3c5dbf2ce1e6fc8b0fcce1a5dfe7c4ec5ab33b76722fcca9cbfff5/pyenchant-2.0.0-py2.py3.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp33.pp35-none-macosx_10_6_intel.macosx_10_9_intel.whl#md5=61afe303ca005dba28b64841fb986f28; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -c "import enchant; enchant._runtestsuite()"; fi

script:
  - true

notifications:
  - email: ryan@rfk.id.au
