name: tests

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install libenchant-dev (linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libenchant-2-dev

      - name: Install enchant (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install enchant

      - name: Install tox
        run: pip install tox

      - name: Run tests with tox
        run: tox -e ${{ matrix.python }}
