name: tests

on: [push]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.5, 3.6, 3.7, 3.8, pypy3]
        include:
         - os: ubuntu-latest
           platform: linux
         - os: macos-latest
           platform: macos
         - os: ubuntu-latest
           platform: linux
         - os: windows-latest
           platform: windows

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install libenchant-dev (linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt install libenchant-dev

    - name: Install enchant (macOS)
      if: matrix.platform == 'macos'
      run: |
        brew update
        brew install enchant

    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.create false
        python -m poetry install

    - name: Run tests
      run: |
        python -m poetry run invoke bootstrap
        python -m poetry run pytest --cov . --cov-report term

