name: tests

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "pypy-3.11"]
        include:
          - python: "3.9"
            tox_env: "py39"
          - python: "3.10"
            tox_env: "py310"
          - python: "3.11"
            tox_env: "py311"
          - python: "3.12-"
            tox_env: "py312"
          - python: "3.13"
            tox_env: "py313"
          - python: "pypy-3.11"
            tox_env: "pypy3"
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install libenchant-dev (linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt install libenchant-2-dev

      - name: Install enchant (macOS)
        if: matrix.platform == 'macos'
        run: |
          brew install enchant

      - name: Install tox
        run: |
          pip install tox

      - name: Run tests
        run: |
          tox -e ${{ matrix.tox_env }}
